#pragma once

#define RICH_MENU_COPY 101
#define RICH_MENU_SELECTALL 102

#define CONSOLE_MENU_RESTORE 103
#define CONSOLE_MENU_ABOUT 104
#define CONSOLE_MENU_EXIT 105

#define CONSOLE_MAINMENU_SAVELOG 106
#define CONSOLE_MAINMENU_CLEARLOG 107

#define WM_SHOWBALOON WM_USER + 3000
#define WM_RBUTTONMENU WM_USER + 3001